version: 2.1
jobs:
  crunch:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/cimr-d
    #resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install git-lfs
          command: |
            bash .circleci/git_lfs.sh
            git lfs install && git lfs pull
      - add_ssh_keys:
          fingerprints:
            - "2e:fb:e9:d5:94:c6:f4:75:2c:cb:66:71:a9:af:93:8a"
      - run:
          name: Install cimr and its dependencies
          command: |
            bash .circleci/install_cimr.sh
      - run:
          name: Handle user request
          command: |
            bash .circleci/handle_request.sh
      - persist_to_workspace:
          root: ~/cimr-d
          paths:
            - .git
            - .circleci
            - submitted
            - processed
            - submitted_data
            - processed_data

  deploy:
    docker:
      - image: circleci/python:3.6.8
    working_directory: ~/cimr-d
    steps:
      - attach_workspace:
          at: ~/cimr-d
      - add_ssh_keys:
          fingerprints:
            - "9e:7e:ab:ae:31:9b:02:2e:46:af:a8:6b:bc:f8:72:99"
      - run:
          name: Save submitted and processed data
          command: |
            bash .circleci/git_lfs.sh
            bash .circleci/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - crunch
      - deploy:
          requires:
            - crunch
          filters:
            branches:
              only: master
